# Generated by Django 6.0.4 on 2026-04-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='ConfigSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='Tropic Visual', help_text='Título que aparece en la pestaña del navegador', max_length=200)),
                ('nombre_propietario', models.CharField(default='Miguel Acosta', help_text='Nombre del dueño del portafolio', max_length=200)),
                ('subtitulo', models.CharField(blank=True, default='Photographer & Videomaker — Capturando momentos únicos', help_text='Texto debajo del nombre en la página de inicio', max_length=300)),
                ('bio', models.TextField(blank=True, default='We are a creative duo specializing in photography and videography, passionate about capturing unique moments and telling stories through our lens. With a keen eye for detail and a love for visual storytelling, we strive to create compelling content that resonates with our audience.', help_text='Texto de la página Sobre Mí')),
                ('imagen_hero', models.ImageField(blank=True, help_text='Imagen de fondo del encabezado/hero', upload_to='sitio/')),
                ('imagen_fondo', models.ImageField(blank=True, help_text='Imagen de fondo general de la página', upload_to='sitio/')),
                ('logo', models.ImageField(blank=True, help_text='Logo que aparece en la barra de navegación', upload_to='sitio/')),
                ('meta_description', models.CharField(blank=True, help_text='Descripción para motores de búsqueda (máx. 160 caracteres)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas (ej: fotografía, video, portafolio)', max_length=255)),
                ('instagram', models.URLField(blank=True, help_text='URL de perfil de Instagram')),
                ('facebook', models.URLField(blank=True, help_text='URL de perfil de Facebook')),
                ('linkedin', models.URLField(blank=True, help_text='URL de perfil de LinkedIn')),
                ('twitter', models.URLField(blank=True, help_text='URL de perfil de Twitter / X')),
                ('pinterest', models.URLField(blank=True, help_text='URL de perfil de Pinterest')),
                ('youtube', models.URLField(blank=True, help_text='URL de canal de YouTube')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('foto', 'Fotografía'), ('video', 'Video')], max_length=5)),
                ('imagen_portada', models.ImageField(upload_to='portadas/')),
                ('fecha', models.DateField()),
                ('destacado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='galeria.categoria')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video (archivo)'), ('video_url', 'Video (URL externa)')], max_length=10)),
                ('archivo', models.FileField(blank=True, upload_to='media_items/')),
                ('url_externa', models.URLField(blank=True, help_text='URL de YouTube/Vimeo para videos externos')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='galeria.proyecto')),
            ],
            options={
                'verbose_name': 'elemento multimedia',
                'verbose_name_plural': 'elementos multimedia',
                'ordering': ['orden'],
            },
        ),
    ]
